project_id = "yvfkkdvhizjdpouoewch"

[functions.chamon-query]
verify_jwt = false

[functions.chamon-create-task]
verify_jwt = false

[functions.chamon-create-mission]
verify_jwt = false

[functions.chamon-update-task]
verify_jwt = false

[functions.send-digest-cron]
verify_jwt = false
