/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated.today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated.agent'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated.achievements'
import { Route as AuthenticatedOperationsVistaPelicanRouteImport } from './routes/_authenticated.operations.vista-pelican'
import { Route as AuthenticatedOperationsReservationsRouteImport } from './routes/_authenticated.operations.reservations'
import { Route as AuthenticatedMissionsIdRouteImport } from './routes/_authenticated.missions.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsVistaPelicanRoute =
  AuthenticatedOperationsVistaPelicanRouteImport.update({
    id: '/operations/vista-pelican',
    path: '/operations/vista-pelican',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsReservationsRoute =
  AuthenticatedOperationsReservationsRouteImport.update({
    id: '/operations/reservations',
    path: '/operations/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsIdRoute = AuthenticatedMissionsIdRouteImport.update({
  id: '/missions/$id',
  path: '/missions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/operations/reservations': typeof AuthenticatedOperationsReservationsRoute
  '/operations/vista-pelican': typeof AuthenticatedOperationsVistaPelicanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/operations/reservations': typeof AuthenticatedOperationsReservationsRoute
  '/operations/vista-pelican': typeof AuthenticatedOperationsVistaPelicanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/_authenticated/operations/reservations': typeof AuthenticatedOperationsReservationsRoute
  '/_authenticated/operations/vista-pelican': typeof AuthenticatedOperationsVistaPelicanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/agent'
    | '/calendar'
    | '/contacts'
    | '/dashboard'
    | '/settings'
    | '/today'
    | '/missions/$id'
    | '/operations/reservations'
    | '/operations/vista-pelican'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/agent'
    | '/calendar'
    | '/contacts'
    | '/dashboard'
    | '/settings'
    | '/today'
    | '/missions/$id'
    | '/operations/reservations'
    | '/operations/vista-pelican'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/agent'
    | '/_authenticated/calendar'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/missions/$id'
    | '/_authenticated/operations/reservations'
    | '/_authenticated/operations/vista-pelican'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/vista-pelican': {
      id: '/_authenticated/operations/vista-pelican'
      path: '/operations/vista-pelican'
      fullPath: '/operations/vista-pelican'
      preLoaderRoute: typeof AuthenticatedOperationsVistaPelicanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/reservations': {
      id: '/_authenticated/operations/reservations'
      path: '/operations/reservations'
      fullPath: '/operations/reservations'
      preLoaderRoute: typeof AuthenticatedOperationsReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/$id': {
      id: '/_authenticated/missions/$id'
      path: '/missions/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof AuthenticatedMissionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedMissionsIdRoute: typeof AuthenticatedMissionsIdRoute
  AuthenticatedOperationsReservationsRoute: typeof AuthenticatedOperationsReservationsRoute
  AuthenticatedOperationsVistaPelicanRoute: typeof AuthenticatedOperationsVistaPelicanRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedMissionsIdRoute: AuthenticatedMissionsIdRoute,
  AuthenticatedOperationsReservationsRoute:
    AuthenticatedOperationsReservationsRoute,
  AuthenticatedOperationsVistaPelicanRoute:
    AuthenticatedOperationsVistaPelicanRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
